### ISSUE TITLE
Verify Support for Django 3.2

### ISSUE THREAD

**Issue by wayfarer1549** [didorothy/wagtailaltstreamfield#53]
Attempting to install requirements for a Django 3.2 project in a fresh virtual environment encounters a dependency conflict since `wagtailaltstreamfield` is listed as only supporting through Django 2.2.

**Comment by didorothy** [comment]
I actually had made several changes in preparation for this but somehow I had neglected to commit them. The 0.12 version should now reflect the support for Django 3.2.
